name: Second Pipeline
on:
  workflow_run:
    workflows: [first_pipe]
    types: [completed]

jobs:
  second_pipe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Starting Deploying the Application"
          echo "Application Deployed"
    
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: first_pipe.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: docker-build-artifacts
          if_no_artifact_found: fail

      - name: Display structure of downloaded files
        run: ls -R

      - name: set env variables
        run: |
          echo "base_url=$(cat base_url.txt)" >> $GITHUB_ENV
          echo "sha_short=$(cat sha_short.txt)" >> $GITHUB_ENV
          echo "base_url=$(cat base_url.txt)"
          echo "sha_short=$(cat sha_short.txt)"
