name: Second Pipeline
on:
  workflow_run:
    workflows: ["First Pipe"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Starting Deploying the Application"
          echo "Application Deployed"